FROM alpine:3.21

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata

COPY $TARGETPLATFORM/picoclaw /usr/local/bin/picoclaw
COPY docker/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh && \
    addgroup -g 1000 picoclaw && \
    adduser -D -u 1000 -G picoclaw picoclaw

USER picoclaw

ENTRYPOINT ["/entrypoint.sh"]
